default: &default
  adapter: postgresql
  encoding: unicode
  username: DojoSecrets
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: DojoSecrets_development

test:
  <<: *default
  database: DojoSecrets_test

production:
  <<: *default
  database: DojoSecrets_production
  password: <%= ENV['DOJOSECRETS_DATABASE_PASSWORD'] %>


